---
- name: Deploy Docker Backend
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    repo_folder: git@github.com:Hannes221/bellfood_start_2024.git
    project_folder: bellfood/
    backend_src: bellfood/backend/
  tasks:
    - git:
        repo: '{{ repo_folder }}'
        dest: '{{ project_folder }}'
        update: yes

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: '{{ backend_src }}'
        state: absent
      become: true

    - name: Start container
      community.docker.docker_compose:
        project_src: '{{ backend_src }}'
        build: yes
      register: compose_output
      become: true
