version: '3'
services:
  backend:
    image: python:3.11
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/app/backend
    ports:
      - '8000:8000'
    command:
      [
        'uvicorn',
        '--host',
        '0.0.0.0',
        '--port',
        '8000',
        'backend.src.app:app',
        '--reload',
      ]

  redis:
    image: redis:7.0
